name: Doc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docgen-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Generate Documentation
      uses: xubaiw/actions-doc-gen4@5ad4ea40c61458a2ffbfaa62019295d738cfc1e9
      with:
        modules: Socket
        root-url: /Socket.lean/
        doc-gen4-repo: https://github.com/xubaiw/doc-gen4.git
        doc-gen4-checkout: 0b9a9f0bdc96911996aa7f1ccf133e53d8a62287

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages 
        folder: build/doc